### PR TITLE
Create package.json

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by hakimel** [comment]
Good stuff, thanks.

**Comment by PeterDaveHello** [comment]
No problem, BTW, would you like to add cdn info in readme?
We have Meny on cdnjs here https://cdnjs.com/libraries/meny

**Comment by hakimel** [comment]
Sure – added a note about it in 1d05ffbf2e36f3106e800ac98dda7fdd2c1655e1

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
